### ISSUE TITLE
Add missing docstrings

### ISSUE THREAD

**Issue by 5A11** [fetchai/cosmpy#126]
This is a tracking issue for missing docstrings in CosmPy. We need to prioritise the Aerial package which upon completion unblocks #225. The following error codes are disabled. One by one we should enable and fix the issues:

- [x] DAR401: Missing exception(s) in Raises section in docstrings
- [x] D202: 1 blank line required between summary line and description in docstrings
- [x] D205: No blank lines allowed after function docstring in docstrings
- [x] D400: First line should end with a period in docstrings
- [x] D401: First line should be in imperative mood in docstrings
- [ ] D403: First word of the first line should be properly capitalized in docstrings

**Comment by VijaySharma815** [comment]
PR: https://github.com/fetchai/cosmpy/pull/217

**Comment by VijaySharma815** [comment]
WIP PR: https://github.com/fetchai/cosmpy/pull/265

**Comment by 5A11** [comment]
Closing this issue as most are applied. Will do another round of cleanup later.
