### ISSUE TITLE
Feature request: Make passing address to contracts easier

### ISSUE THREAD

**Issue by dishmop** [fetchai/cosmpy#169]
### Prerequisites

- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and made sure this feature does not already exist.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure this feature has not already been requested.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Problem

When passing addresses of either wallets or contracts to contracts, it is very verbose. e.g.
```
    cc.agbp.execute(
        {
            "mint": {
                "recipient": str(acc_borrower.address()),
                "amount": str(5 * cc.one_unit)
            }
        }, acc_admin).wait_to_complete()
```
        

### Feature / Solution

`str(acc_borrower.address())`, should just be `acc_borrower`

Similarly when passing in address of contracts:
`str(cc.atomix_mint.address)`

**Comment by 5A11** [comment]
This is in #204.

**Comment by 5A11** [comment]
This is now in under #204

**Comment by 5A11** [comment]
Are you happy with this implementation @dishmop?

**Comment by dishmop** [comment]
That looks great - thanks
