### ISSUE TITLE
Feature request: Get stack trace from returned contract errors

### ISSUE THREAD

**Issue by dishmop** [fetchai/cosmpy#171]
### Prerequisites

- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and made sure this feature does not already exist.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure this feature has not already been requested.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Problem

When my contracts return an error to cosmpy, then I often see the error message but have no idea where it arose (not even which contract it came from - as it could have come from a contract calling another contract etc.)

### Feature / Solution

I'd like to run a local node with an option to return the stack trace on error.

**Comment by solarw** [comment]
suppose it's relative:
https://github.com/wasmerio/wasmer/issues/827

**Comment by 5A11** [comment]
This and https://github.com/fetchai/cosmpy/issues/172 are not possible to address in CosmPy. Please reopen in another repo where this belongs.
