### ISSUE TITLE
Feature request: Get Stack trace on panic!()

### ISSUE THREAD

**Issue by dishmop** [fetchai/cosmpy#172]
### Prerequisites

- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and made sure this feature does not already exist.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure this feature has not already been requested.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Problem

when developing and running a local node, if my code panic!() in the contract (perhaps through an unwrap or whatever) I have no idea what caused it or where it panicked.

### Feature / Solution

It would be great to see the stack trace of the error somewhere. 

Ideally it would be returned to the calling code, but even if it was outputed to the terminal in way that we can grep it.

**Comment by 5A11** [comment]
This and #171 are not possible to address in CosmPy. Please reopen in another repo where this belongs.
