### ISSUE TITLE
Feature request: Add StakingAuthorization

### ISSUE THREAD

**Issue by Alejandro-Morales** [fetchai/cosmpy#174]
### Prerequisites

- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and made sure this feature does not already exist.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure this feature has not already been requested.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Feature / Solution

Add StakingAuthorization and possibly other more specific types of authorization.

**Comment by solarw** [comment]
@Alejandro-Morales 
please check `from cosmpy.protos.cosmos.staking.v1beta1.authz_pb2 import StakeAuthorization`
suppose it will work for you
