### ISSUE TITLE
Use case: liquidity pool trading

### ISSUE THREAD

**Issue by jrriehl** [fetchai/cosmpy#184]
### Prerequisites

- [X] I am running the [latest CosmPy version](https://docs.fetch.ai/CosmPy/#version).
- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and found no answer to my problem.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure my problem has not already been reported.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Expected Behavior

Demonstrate use of CosmPy for liquidity pool trading on Starfleit DEX.

### Current Behavior

Not implemented.

**Comment by 5A11** [comment]
This is in now #186. Waiting for its use-case documentation.

**Comment by 5A11** [comment]
Added in #186
