### ISSUE TITLE
Feature request: Update examples with FaucetApi and argparse

### ISSUE THREAD

**Issue by Alejandro-Morales** [fetchai/cosmpy#201]
### Prerequisites

- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and made sure this feature does not already exist.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure this feature has not already been requested.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Problem

* Some CosmPy examples don't include the FaucetApi that allows adding tokens to a specific address in CosmPy. Before it was assumed that the address had tokens.
* Also, a couple of examples don't include argparse

### Feature / Solution

Revise CosmPy examples and add features needed

**Comment by 5A11** [comment]
Added in #203
