### ISSUE TITLE
Add integration tests involving non-fetchai chains 

### ISSUE THREAD

**Issue by 5A11** [fetchai/cosmpy#214]
### Prerequisites

- [X] I am running the [latest CosmPy version](https://docs.fetch.ai/CosmPy/#version).
- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and found no answer to my problem.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure my problem has not already been reported.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Expected Behavior

There should be integration tests that test main cosmpy behaviours when interacting with non-fetch.ai chains.

### Current Behavior

There are no integration tests currently involving non-fetch.ai chains

### Context

All

**Comment by ejfitzgerald** [comment]
I guess the two main ones should be:

- cosmoshub
- osmosis

**Comment by 5A11** [comment]
Added in PR #227
