### ISSUE TITLE
Integration tests for REST API

### ISSUE THREAD

**Issue by pbukva** [fetchai/cosmpy#22]
Implement integration tests, excersising rest client API of all modules against real instance of Tenderming & Cosmos-SDK based node(for example `fetchd`) runnig locally (preferably in docker container).

The main goal is to verify, that modules rest API scorrectly implemented in end-to-end sesne = all requests created & submitedt by modules rest API are actually successfully processed by blockchain node, and API is a able to successfully deserialise resposses.

> NOTE: This is primarily focused on modules REST API, but tests can be also run using auto-generated gRPC API.

**Comment by 5A11** [comment]
Addressed in #43
