### ISSUE TITLE
Add Reference API

### ISSUE THREAD

**Issue by 5A11** [fetchai/cosmpy#225]
### Prerequisites

- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and made sure this feature does not already exist.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure this feature has not already been requested.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Problem

There is currently no reference API in ComsPy's documentation.

### Feature / Solution

Add reference API in CosmPy's documentation, maybe starting with what's in the Aerial package and then doing something clever on the low-level APIs as well to avoid having a useless protobuf functions.

**Comment by 5A11** [comment]
Can be started after #126 for Aerial package is completed.

**Comment by VijaySharma815** [comment]
PR: https://github.com/fetchai/cosmpy/pull/247

**Comment by 5A11** [comment]
The PR is now merged.
