### ISSUE TITLE
Code quality via wemake-python-styleguide

### ISSUE THREAD

**Issue by 5A11** [fetchai/cosmpy#246]
Consider addressing the issues raised by wemake-python-styleguide as described here https://wkrzywiec.medium.com/how-to-write-good-quality-python-code-with-github-actions-2f635a2ab09a and enabling it in CI.

**Comment by VijaySharma815** [comment]
![Image](https://user-images.githubusercontent.com/54273054/189966403-6918a925-6bec-47bb-ae91-9260145a8935.png)

**Comment by 5A11** [comment]
`wemake-python-styleguide` is actually a `flake8` plugin with [some other plugins](https://wemake-python-styleguide.readthedocs.io/en/latest/pages/usage/violations/index.html#external-plugins) as dependencies.

We can use this tool from time to time to format our code. 


PR: https://github.com/fetchai/cosmpy/pull/269

Reference: https://wkrzywiec.medium.com/how-to-write-good-quality-python-code-with-github-actions-2f635a2ab09a

**Comment by dominic22** [comment]
closed as moved to done
