### ISSUE TITLE
Automate release process in GH workflow

### ISSUE THREAD

**Issue by 5A11** [fetchai/cosmpy#249]
Consider automating as much of CosmPy's release process in GH workflow as possible.

**Comment by solarw** [comment]
https://github.com/fetchai/cosmpy/pull/267

**Comment by 5A11** [comment]
PR: #267

**Comment by 5A11** [comment]
@ejfitzgerald Waiting for PyPI secrets

**Comment by 5A11** [comment]
Done and tested successfully.
