### ISSUE TITLE
Aerial: Cannot just instantiate contract from code_id without having _digest

### ISSUE THREAD

**Issue by MissingNO57** [fetchai/cosmpy#256]
### Prerequisites

- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and made sure this feature does not already exist.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure this feature has not already been requested.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Problem

Aerial API instantiate contract requires _digest to be set making this function fail in the case when we have only code_id and want to instantiate contract from it. 

### Feature / Solution

Make _digest optional

**Comment by lrahmani** [comment]
From the implementation of [`LedgerContract.instantiate`](https://github.com/fetchai/cosmpy/blob/master/cosmpy/aerial/contract/__init__.py#L131), it only uses `digest` for generating a label, in case `label` parameter is not provided

**Comment by dominic22** [comment]
closed as moved to done
