### ISSUE TITLE
Bug report: Error deploying contracts using rest server

### ISSUE THREAD

**Issue by Alejandro-Morales** [fetchai/cosmpy#262]
### Prerequisites

- [X] I am running the [latest CosmPy version](https://docs.fetch.ai/CosmPy/#version).
- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and found no answer to my problem.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure my problem has not already been reported.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Expected Behavior

Should be able to deploy contracts using rest server:

# Network configuration
cfg = NetworkConfig(
chain_id="dorado-1",
url="rest+https://rest-dorado.fetch.ai:443",
fee_minimum_gas_price=1000000000000,
fee_denomination="atestfet",
staking_denomination="atestfet",
)

ledger = LedgerClient(cfg)

### Current Behavior

contract = LedgerContract(contract_path, ledger)

```
ParseError: Failed to parse code_infos field: Message type "cosmwasm.wasm.v1.CodeInfoResponse" has no field named "instantiate_permission".
 Available Fields(except extensions): ['codeId', 'creator', 'dataHash'].
```

### Context

Running:

contract = LedgerContract(contract_path, ledger)

With the following rest configuration:

# Network configuration
cfg = NetworkConfig(
chain_id="dorado-1",
url="rest+https://rest-dorado.fetch.ai:443",
fee_minimum_gas_price=1000000000000,
fee_denomination="atestfet",
staking_denomination="atestfet",
)

ledger = LedgerClient(cfg)

**Comment by solarw** [comment]
Bug confirmed

**Comment by 5A11** [comment]
@MissingNO57 Need help.

**Comment by dominic22** [comment]
closed as moved to done
