### ISSUE TITLE
Add Pagination support in the staking summary of a particular address. 

### ISSUE THREAD

**Issue by VijaySharma815** [fetchai/cosmpy#273]
https://github.com/fetchai/cosmpy/blob/master/cosmpy/aerial/client/__init__.py#L288

**Comment by VijaySharma815** [comment]
Hey @5A11 ,

```
>>> from cosmpy.aerial.client import LedgerClient, NetworkConfig
>>> ledger_client = LedgerClient(NetworkConfig.fetch_mainnet())
>>> address = "fetch1w0xakws230s78vyydl75mv8ujrt5vs7uujzlwe"
>>> res = ledger_client.query_staking_summary(address)
>>> res
StakingSummary(current_positions=[StakingPosition(validator='fetchvaloper1xrlqqepyfl64mjr8x837y5slxfzlywe57rwdta', amount=999999999999990, reward=273060486305), StakingPosition(validator='fetchvaloper18tmu0lrfsdvke8e3a3jsd7fq2rs29krf8kmpsz', amount=99000000000000000, reward=26767675468499), StakingPosition(validator='fetchvaloper1dafx5uk2zvsz43dz05gzx78vmnq3wu9rg4lmgg', amount=9999999000000000, reward=2938129426962)], unbonding_positions=[])
```

For pagination support,

- What will be the response schema after pagination support 
- By default how much data do we need to return (10 staking positions and 10 unbonding positions)?

**Comment by VijaySharma815** [comment]
response from ED:

this is about fully handling the response from the ledger node: Here is the example for the staking case:
https://github.com/fetchai/cosmpy/blob/master/cosmpy/aerial/client/__init__.py#L287-L288

To fully understand it you need to look at the protobuf definition here:
https://github.com/fetchai/cosmos-sdk/blob/master/proto/cosmos/staking/v1beta1/query.proto#L217-L223

You can see from the cosmpy code we only bother to process the first page of the results from the client. In general, this is fine for most cases, but it is not correct. Specifically, the cosmpy code does not even read the pagination attribute to ensure that this is the only page available.
The definition for the PageResponse is here:
https://github.com/fetchai/cosmos-sdk/blob/master/proto/cosmos/base/query/v1beta1/pagination.proto#L47-L55

This task will require the query logic to be updated to be in a loop in order to request all the pages before returning the response.
Also since we only don’t really handle pagination across the library, it makes sense to abstract some of the query logic so that we can be reused for other cases too

**Comment by 5A11** [comment]
Pending the fix for windows CI issue

**Comment by 5A11** [comment]
@solarw please fix the CI failures.
