### ISSUE TITLE
Investigate osmosis integration test issue

### ISSUE THREAD

**Issue by solarw** [fetchai/cosmpy#275]
### Prerequisites

- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and made sure this feature does not already exist.
- [X] I checked the existing issues to make sure this feature has not already been requested.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Problem

Osmosis integration test does not work anymore.
Even account has positive balance, tx submission says `account not found`.

### Feature / Solution

The investigation is required for osmosis integration test.
Looks like it osmosis side issue, but need a confirmation.
Probably connect osmosis team.

**Comment by solarw** [comment]
for the moment osmosis testnet faucet does not work:
error 522, cors error.

**Comment by solarw** [comment]
faucet works,
account funded well, checked via API and testnet explorer
on tx settle says `account not found` (like not funded at all)

**Comment by 5A11** [comment]
@MissingNO57 Need help.

**Comment by 5A11** [comment]
Tests are still failing. @solarw please check manually if their test-net is still down.
