### ISSUE TITLE
Code quality via wemake-python-styleguide

### ISSUE THREAD

**Issue by VijaySharma815** [fetchai/cosmpy#281]
`wemake-python-styleguide` is actually a `flake8` plugin with [some other plugins](https://wemake-python-styleguide.readthedocs.io/en/latest/pages/usage/violations/index.html#external-plugins) as dependencies.

We can use this tool from time to time to format our code. 

PR: https://github.com/fetchai/cosmpy/pull/269

Reference: https://wkrzywiec.medium.com/how-to-write-good-quality-python-code-with-github-actions-2f635a2ab09a

**Comment by 5A11** [comment]
Added to the original issue #246
