### ISSUE TITLE
Bug report: QueryValidatorsResponse ParseError in REST API

### ISSUE THREAD

**Issue by Widlar** [fetchai/cosmpy#284]
### Prerequisites

- [X] I am running the [latest CosmPy version](https://docs.fetch.ai/CosmPy/#version).
- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and found no answer to my problem.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure my problem has not already been reported.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Expected Behavior

Using the REST version of the API, I am trying to get a list of Mainnet network validators. 

### Current Behavior

The server response cannot be turned into the protobuf message QueryValidatorsResponse. 
The error occurs in the consensus_pubkey field.
That being said, I tried compiling my proto files for newer versions of Cosmos SDK, but the problem persists.

### To Reproduce

This error is shown by the following code:
```python 
from cosmpy.aerial.client import LedgerClient, NetworkConfig
cfg = NetworkConfig(
    chain_id='fetchhub-4',
    url='rest+https://rest-fetchhub.fetch.ai',
    fee_minimum_gas_price=0,
    fee_denomination="afet",
    staking_denomination="afet",
    faucet_url=None,
)

ledger_client = LedgerClient(cfg)
validators = ledger_client.query_validators()
print(validators) `

### Context

My OS: Windows 10, I'm using cosmpy==0.5.1 (compiling main from github) and Python 3.8.0.

### Failure Logs

```
File "C:\Users\Sergey\Anaconda3\envs\sergey\lib\site-packages\google\protobuf\json_format.py", line 648, in _ConvertAnyMessage
    raise ParseError('{0} at {1}'.format(e, path))
google.protobuf.json_format.ParseError: Can not find message descriptor by type_url: /cosmos.crypto.ed25519.PubKey at QueryValidatorsResponse.validators[0].consensus_pubkey
`

**Comment by Widlar** [comment]
I thought about it and was able to solve this problem by simply adding to the file: 

> cosmpy\aerial\client\__init__.py

import: 
```python 
from cosmpy.protos.cosmos.crypto.ed25519.keys_pb2 import PubKey
```
This import itself is not used directly, but is needed when turning proto messages into a dictionary. I will create Pull requests.

**Comment by solarw** [comment]
https://github.com/fetchai/cosmpy/pull/294 fixed
