### ISSUE TITLE
Support mnemonic

### ISSUE THREAD

**Issue by 5A11** [fetchai/cosmpy#75]
Add support for mnemonic (e.g. mnemonic to private key and vice versa conversion)

**Comment by daeMOn63** [comment]
Would also be great to have some extra utils:
- derive bech32 address from pubkey
- derive pubkey from privkey

**Comment by Teasel-Ian** [comment]
I've PR'ed a [bip_utils example](https://github.com/fetchai/cosmpy/pull/143/commits/a6cdf2cbf40cf4f0c6c66c569f2865e20192cd84) of how to derive a private key from a mnemonic (not sure the reverse is possible?), but it would be great to have this supported in cosmpy itself!

**Comment by solarw** [comment]
already done: https://github.com/fetchai/cosmpy/blob/master/cosmpy/aerial/wallet.py#L51

**Comment by 5A11** [comment]
Closing as this is already in as solarw pointed above.
